version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_container
    environment:
      - 'MYSQL_DATABASE=person'
      - 'MYSQL_PASSWORD=102030'
      - 'MYSQL_ROOT_PASSWORD=102030'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'
    networks:
      - people

networks:
  people:
